export const ErrorCodes = {
  ERR_INVALID_ADDRESS: 'ERR_INVALID_ADDRESS',
  ERR_INVALID_AMOUNT: 'ERR_INVALID_AMOUNT',
  ERR_MISSING_ASSET: 'ERR_MISSING_ASSET',
  ERR_MISSING_QUERY: 'ERR_MISSING_QUERY',
  ERR_NOT_FEDERATED: 'ERR_NOT_FEDERATED',
  ERR_NOT_FOUND: 'ERR_NOT_FOUND',
  ERR_LOOKUP_FAILED: 'ERR_LOOKUP_FAILED',
  ERR_NO_PATH_FOUND: 'ERR_NO_PATH_FOUND',
  ERR_SLIPPAGE_EXCEEDED: 'ERR_SLIPPAGE_EXCEEDED',
  ERR_STALE_QUOTE: 'ERR_STALE_QUOTE',
  ERR_NETWORK_FAILURE: 'ERR_NETWORK_FAILURE',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export function apiError(code: ErrorCode, message: string) {
  return { error: `${code}: ${message}` }
}
